### ISSUE TITLE
Python机器学习开发环境 | BerMaker

### ISSUE THREAD

**Issue by zhongchun** [zhongchun/gitalk#10]
http://yuzhongchun.us/2018/11/15/2-python-machine-learning/ 

 Python是著名的“龟叔”Guido van Rossum在1989年圣诞节期间，为了打发无聊的圣诞节而编写的一个编程语言。Python的哲学就是简单优雅，尽量写容易看明白的代码，尽量写少的代码。
目前，Python是机器学习实验、测试和

**Comment by bermaker** [comment]
这几个库确实用的很多，收藏了☺
