### ISSUE TITLE
Hello World | BerMaker

### ISSUE THREAD

**Issue by zhongchun** [zhongchun/gitalk#2]
http://yuzhongchun.us/2019/01/27/hello-world/ 

 Welcome to Hexo! This is your very first post. Check documentation for more info. If you get any problems when using Hex

**Comment by zhongchun** [comment]
hi

**Comment by zhongchun** [comment]
> @zhongchun
> hi

**Comment by bermaker** [comment]
> @zhongchun
> > @zhongchun
> > hi
> 
> 

hello
